name: 🐛 Bug Report
description: Сообщить об ошибке в расширении
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за сообщение об ошибке! 🐛
        
  - type: textarea
    id: description
    attributes:
      label: Описание проблемы
      description: Кратко опишите что пошло не так
      placeholder: |
        Например: "При форматировании файла с вложенными if блоками отступы неправильные"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Шаги для воспроизведения
      description: Как воспроизвести проблему?
      placeholder: |
        1. Открыть файл с кодом...
        2. Нажать Shift+Alt+F для форматирования
        3. Увидеть неправильные отступы в строке X
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
      description: Что должно было произойти?
      placeholder: Отступы должны быть правильными
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Фактическое поведение
      description: Что произошло вместо этого?
      placeholder: Отступы сдвинулись неправильно
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Пример кода (если применимо)
      description: Минимальный пример PML кода, который вызывает проблему
      render: pml
      placeholder: |
        define method .test()
          if (condition) then
            -- код
          endif
        endmethod

  - type: dropdown
    id: version
    attributes:
      label: Версия расширения
      description: Какая версия PML for AVEVA E3D установлена?
      options:
        - 0.4.8 (latest)
        - 0.4.7
        - 0.4.6
        - 0.4.5
        - Other (укажи в комментарии)
    validations:
      required: true

  - type: dropdown
    id: vscode-version
    attributes:
      label: Версия VS Code / Cursor
      description: Help → About
      options:
        - VS Code 1.85+
        - VS Code 1.80-1.84
        - Cursor latest
        - Other (укажи в комментарии)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Операционная система
      options:
        - Windows 11
        - Windows 10
        - Windows Server
        - Linux
        - macOS
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Логи (если есть)
      description: |
        Ctrl+Shift+P → "Developer: Toggle Developer Tools" → Console
        Скопируй сообщения об ошибках (если есть)
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Чек-лист
      options:
        - label: Я проверил что проблема воспроизводится на последней версии
        - label: Я проверил что похожий issue ещё не создан
        - label: Я включил пример кода (если применимо)

